module.exports = {
  //state
  SIGNED_IN: "SIGNED_IN",
  ANONYMOUS: "ANONYMOUS",
  AWAITING: "AWAITING",
  //actions
  ATTEMPTING: "ATTEMPTING",
	SIGNIN_USER: "SIGNIN_USER",
	CHANGE_USER_ATTENDS: "CHANGE_USER_ATTENDS",
	LOGOUT: "LOGOUT"
}
