module.exports = {
  //state
  //actions
  UPDATE_LOCATION: "UPDATE_LOCATION",
  UPDATE_TAGS: "UPDATE_TAGS",
  DRAW_CIRCLE: "DRAW_CIRCLE",
  SUGGEST_TIME: "SUGGEST_TIME",
  SUGGEST_DAY: "SUGGEST_DAY"
}
