module.exports = {
  //states
  LOADED: "LOADED",
  NOT_LOADED: "NOT_LOADED",
  LOADING: "LOADING",
  //actions
  LOADING_NOTIFICATIONS: "LOADING_NOTIFICATIONS",
  UPDATE_NOTIFICATIONS: "UPDATE_NOTIFICATIONS"
}
