module.exports = {
  //states
  LOADED: "LOADED",
  NOT_LOADED: "NOT_LOADED",
  LOADING: "LOADING",
  NO_NOTIFICATIONS_STATE: "NO_NOTIFICATIONS_STATE",
  //actions
  NO_NOTIFICATIONS: "NO_NOTIFICATIONS",
  LOADING_NOTIFICATIONS: "LOADING_NOTIFICATIONS",
  UPDATE_NOTIFICATIONS: "UPDATE_NOTIFICATIONS"
}
