module.exports = {
  //state
  //actions
  UPDATE_LOCATION_SEARCH_SEARCH: "UPDATE_LOCATION_SEARCH",
  UPDATE_TAGS_SEARCH: "UPDATE_TAGS_SEARCH",
  UPDATE_EVENTS: "UPDATE_EVENTS",
  UPDATE_FIELDS_SEARCH: "UPDATE_FIELDS_SEARCH",
  CHANGE_USER_ATTENDANT_STATE: "CHANGE_USER_ATTENDANT_STATE",
  UPDATE_COST: "UPDATE_COST",
  UPDATE_NAME: "UPDATE_NAME"
}
